name: Build and Push Docker Image for Project 5

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags like v1.0.0, v1.1.0
    branches:
      - main  # Trigger on push to main branch as well (optional)

jobs:
  build_and_push:
    name: Build Docker Image and Push to Docker Hub
    runs-on: ubuntu-latest  # Runner environment

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Check out the code so that Dockerfile and app are available

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Set up Docker Buildx for better multi-platform support

    - name: Login to DockerHub
      uses: docker/login-action@v1  # Log in to DockerHub using secrets
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Use DockerHub username from secrets
        password: ${{ secrets.DOCKER_TOKEN }}  # Use DockerHub token from secrets

    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v2  # Docker build and push action
      with:
        context: ./project5  # Set build context to project5 (change to project4 if needed)
        push: true  # Push the image to DockerHub
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest  # Tag with latest
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.sha }}  # Tag with commit SHA
          ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ github.ref_name }}  # Tag with version tag (e.g., v1.0.0)

