name: Build and Push Docker Image for Project 5

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on version tags, like v1.0.0, v1.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build Docker Image for Project 5 from p4
    - name: Build and push Docker image for Project 5
      uses: docker/build-push-action@v2
      with:
        context: ./project5  # Build the Docker image from the project4 directory
        push: true
        tags: |
          user/repository:project5-${{ github.ref_name }}  # Tag with version tag (v1.0.0)
          user/repository:latest  # Tag with 'latest'
          user/repository:project5-${{ github.ref_name }}-major  # Major version
          user/repository:project5-${{ github.ref_name }}-major.minor  # Major.minor version
